#!/command/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

cd "${APP_DIR}/frontend" || exit 1

# Override HOST/PORT to avoid conflict with backend env vars
export HOST="0.0.0.0"
export PORT="3000"

exec s6-setuidgid hotio bun ./build/index.js
